#ifndef ANALYSISHARNESS_D_ARCHITECTURE_CHECK_ABCONTROLLER_0_H
#define ANALYSISHARNESS_D_ARCHITECTURE_CHECK_ABCONTROLLER_0_H


#include <stdint.h>

#include <stddef.h>

#include <stdbool.h>

#include "E_Global_Constants.h"

#include "E_Global_Constants.h"

#include "B_Subsystem_Architecture.h"

#include "C_Complex_Data.h"



#ifdef __cplusplus
extern "C" {
#endif

void entryFor__DEEP_abController_Sensor2Phy___Sensor2Phy_blockInstance__Sensor2Phy__cond__Dash_Sensor_Out_constraint_0_Dash_Sensor_Out(void);

void entryFor__DEEP_abController_CarDetection___CarDetection_blockInstance__CarDetection__cond__Grayscale_Value_constraint_0_Threshold_Grayscale(void);

void entryFor__DEEP_abController_CarDetection___CarDetection_blockInstance__CarDetection__cond__Threshold_Grayscale_constraint_1_Threshold_Grayscale(void);

void entryFor__DEEP_abController_CarDetection___CarDetection_blockInstance__CarDetection__cond__Threshold_Pixels_constraint_0_Threshold_Pixels(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__Vehicle_Speed_constraint_0_Vehicle_Speed(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__Dash_Illuminance_constraint_0_Dash_Illuminance(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__FixedOff(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__AutoOff(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__AutoLowBeam(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__FixedLowBeam(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__OpticalHorn(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__AutoHighBeam(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__ParkLights(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__IndependenceLightStates(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__NoBlinding(void);

void entryFor__DEEP_abController_ControlLogic___Fuser___Fuser_blockInstance__Fuser__cond__IndependenceOfStates(void);

void entryFor__DEEP_abController_ControlLogic___HBA___HBA_blockInstance__HBA__cond__Vehicle_Speed_constraint_0_Vehicle_Speed(void);

void entryFor__DEEP_abController_ControlLogic___HLC___HLC_blockInstance__HLC__cond__Dash_Illuminance_constraint_0_Dash_Illuminance(void);

void entryFor__DEEP_abController_postCond__FixedOff(void);

void entryFor__DEEP_abController_postCond__IndependenceLightStates(void);

void single_entry_name_D_Architecture_Check_abController_0(void);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
