#ifndef ANALYSISHARNESS_D_ARCHITECTURE_CHECK_ABCONTROLLER_0_H
#define ANALYSISHARNESS_D_ARCHITECTURE_CHECK_ABCONTROLLER_0_H


#include <stdint.h>

#include <stddef.h>

#include <stdbool.h>

#include "E_Global_Constants.h"

#include "E_Global_Constants.h"

#include "B_Subsystem_Architecture.h"

#include "C_Complex_Data.h"



#ifdef __cplusplus
extern "C" {
#endif

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__FixedOff(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__AutoOff(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__AutoLowBeam(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__FixedLowBeam(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__OpticalHorn(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__AutoHighBeam(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__ParkLights(void);

void entryFor__DEEP_abController_ControlLogic___ControlLogic_blockInstance__ControlLogic__cond__IndependenceLightStates(void);

void entryFor__DEEP_abController_ControlLogic___Fuser___Fuser_blockInstance__Fuser__cond__IndependenceOfStates(void);

void entryFor__DEEP_abController_postCond__FixedOff(void);

void entryFor__DEEP_abController_postCond__IndependenceLightStates(void);

void single_entry_name_D_Architecture_Check_abController_0(void);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
