function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "ATRover"};
	this.sidHashMap["ATRover"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/Sensor_Back_Left"] = {sid: "ATRover:66"};
	this.sidHashMap["ATRover:66"] = {rtwname: "<Root>/Sensor_Back_Left"};
	this.rtwnameHashMap["<Root>/Sensor_Back_Center"] = {sid: "ATRover:67"};
	this.sidHashMap["ATRover:67"] = {rtwname: "<Root>/Sensor_Back_Center"};
	this.rtwnameHashMap["<Root>/Sensor_Back_Right"] = {sid: "ATRover:68"};
	this.sidHashMap["ATRover:68"] = {rtwname: "<Root>/Sensor_Back_Right"};
	this.rtwnameHashMap["<Root>/Sensor_Front_Left"] = {sid: "ATRover:69"};
	this.sidHashMap["ATRover:69"] = {rtwname: "<Root>/Sensor_Front_Left"};
	this.rtwnameHashMap["<Root>/Sensor_Front_Center"] = {sid: "ATRover:70"};
	this.sidHashMap["ATRover:70"] = {rtwname: "<Root>/Sensor_Front_Center"};
	this.rtwnameHashMap["<Root>/Sensor_Front_Right"] = {sid: "ATRover:71"};
	this.sidHashMap["ATRover:71"] = {rtwname: "<Root>/Sensor_Front_Right"};
	this.rtwnameHashMap["<Root>/Drive_Direction "] = {sid: "ATRover:72"};
	this.sidHashMap["ATRover:72"] = {rtwname: "<Root>/Drive_Direction "};
	this.rtwnameHashMap["<Root>/Turn_Direction"] = {sid: "ATRover:73"};
	this.sidHashMap["ATRover:73"] = {rtwname: "<Root>/Turn_Direction"};
	this.rtwnameHashMap["<Root>/Input Conversion"] = {sid: "ATRover:127"};
	this.sidHashMap["ATRover:127"] = {rtwname: "<Root>/Input Conversion"};
	this.rtwnameHashMap["<Root>/Limits"] = {sid: "ATRover:130"};
	this.sidHashMap["ATRover:130"] = {rtwname: "<Root>/Limits"};
	this.rtwnameHashMap["<Root>/Obstacle Detection"] = {sid: "ATRover:131"};
	this.sidHashMap["ATRover:131"] = {rtwname: "<Root>/Obstacle Detection"};
	this.rtwnameHashMap["<Root>/Limited_TR_Left"] = {sid: "ATRover:62"};
	this.sidHashMap["ATRover:62"] = {rtwname: "<Root>/Limited_TR_Left"};
	this.rtwnameHashMap["<Root>/Limited_TR_Right"] = {sid: "ATRover:63"};
	this.sidHashMap["ATRover:63"] = {rtwname: "<Root>/Limited_TR_Right"};
	this.rtwnameHashMap["<Root>/Limited_Speed_Backwards"] = {sid: "ATRover:64"};
	this.sidHashMap["ATRover:64"] = {rtwname: "<Root>/Limited_Speed_Backwards"};
	this.rtwnameHashMap["<Root>/Limited_Speed_Forwards"] = {sid: "ATRover:65"};
	this.sidHashMap["ATRover:65"] = {rtwname: "<Root>/Limited_Speed_Forwards"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
